import "./styles.tmod.css";

export const metadata = {
  title: "TMOD",
  description: "Generated by create next app",
};

export default function tmodLayout({ children }) {
  return <>{children}</>;
}
